### ISSUE TITLE
Scheduler not working as expected

### ISSUE THREAD

**Issue by jsk01** [plexguide/Huntarr.io#556]
I just tested scheduling by setting radarr to enable all instances at 10:00. My time was 9:57.  After checking at 10:05 radarr is still disabled. No errors just this line in the log:
2025-06-03 10:00:43 - huntarr - INFO - Executing enable action for radarr-all

**Comment by Admin9705** [comment]
@jsk01 try 7.5.7. i rewrote it and tested it. I'll check still for what your asking incase.

**Comment by Admin9705** [comment]
@jsk01 resolved in 7.6.2 - it was saving to an incorrect variable.

**Comment by jsk01** [comment]
I just tested again and scheduling still isn't working. I set sonarr to enable at 4:45 daily then sonarr api limits to 20 at 5:00. Neither happened.  Looks like the daily disable all apps at 4:30 worked.

![Image](https://github.com/user-attachments/assets/c6c68f82-6898-49ae-8eb5-9ff124a6188b)

**Comment by Admin9705** [comment]
i'll check again @jsk01
